# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/misha/dev/avr/io_selector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/misha/dev/avr/io_selector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misha/dev/avr/io_selector/CMakeFiles /home/misha/dev/avr/io_selector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misha/dev/avr/io_selector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named disassemble_iss_switch

# Build rule for target.
disassemble_iss_switch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disassemble_iss_switch
.PHONY : disassemble_iss_switch

# fast build rule for target.
disassemble_iss_switch/fast:
	$(MAKE) -f CMakeFiles/disassemble_iss_switch.dir/build.make CMakeFiles/disassemble_iss_switch.dir/build
.PHONY : disassemble_iss_switch/fast

#=============================================================================
# Target rules for targets named get_calibration

# Build rule for target.
get_calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_calibration
.PHONY : get_calibration

# fast build rule for target.
get_calibration/fast:
	$(MAKE) -f CMakeFiles/get_calibration.dir/build.make CMakeFiles/get_calibration.dir/build
.PHONY : get_calibration/fast

#=============================================================================
# Target rules for targets named set_fuses

# Build rule for target.
set_fuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_fuses
.PHONY : set_fuses

# fast build rule for target.
set_fuses/fast:
	$(MAKE) -f CMakeFiles/set_fuses.dir/build.make CMakeFiles/set_fuses.dir/build
.PHONY : set_fuses/fast

#=============================================================================
# Target rules for targets named get_fuses

# Build rule for target.
get_fuses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_fuses
.PHONY : get_fuses

# fast build rule for target.
get_fuses/fast:
	$(MAKE) -f CMakeFiles/get_fuses.dir/build.make CMakeFiles/get_fuses.dir/build
.PHONY : get_fuses/fast

#=============================================================================
# Target rules for targets named iss_switch

# Build rule for target.
iss_switch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iss_switch
.PHONY : iss_switch

# fast build rule for target.
iss_switch/fast:
	$(MAKE) -f CMakeFiles/iss_switch.dir/build.make CMakeFiles/iss_switch.dir/build
.PHONY : iss_switch/fast

#=============================================================================
# Target rules for targets named iss_switch.elf

# Build rule for target.
iss_switch.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iss_switch.elf
.PHONY : iss_switch.elf

# fast build rule for target.
iss_switch.elf/fast:
	$(MAKE) -f CMakeFiles/iss_switch.elf.dir/build.make CMakeFiles/iss_switch.elf.dir/build
.PHONY : iss_switch.elf/fast

#=============================================================================
# Target rules for targets named set_calibration

# Build rule for target.
set_calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 set_calibration
.PHONY : set_calibration

# fast build rule for target.
set_calibration/fast:
	$(MAKE) -f CMakeFiles/set_calibration.dir/build.make CMakeFiles/set_calibration.dir/build
.PHONY : set_calibration/fast

#=============================================================================
# Target rules for targets named get_status

# Build rule for target.
get_status: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_status
.PHONY : get_status

# fast build rule for target.
get_status/fast:
	$(MAKE) -f CMakeFiles/get_status.dir/build.make CMakeFiles/get_status.dir/build
.PHONY : get_status/fast

#=============================================================================
# Target rules for targets named size

# Build rule for target.
size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size
.PHONY : size

# fast build rule for target.
size/fast:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/build
.PHONY : size/fast

#=============================================================================
# Target rules for targets named upload_iss_switch

# Build rule for target.
upload_iss_switch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_iss_switch
.PHONY : upload_iss_switch

# fast build rule for target.
upload_iss_switch/fast:
	$(MAKE) -f CMakeFiles/upload_iss_switch.dir/build.make CMakeFiles/upload_iss_switch.dir/build
.PHONY : upload_iss_switch/fast

#=============================================================================
# Target rules for targets named upload_eeprom

# Build rule for target.
upload_eeprom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_eeprom
.PHONY : upload_eeprom

# fast build rule for target.
upload_eeprom/fast:
	$(MAKE) -f CMakeFiles/upload_eeprom.dir/build.make CMakeFiles/upload_eeprom.dir/build
.PHONY : upload_eeprom/fast

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/iss_switch.elf.dir/build.make CMakeFiles/iss_switch.elf.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/iss_switch.elf.dir/build.make CMakeFiles/iss_switch.elf.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/iss_switch.elf.dir/build.make CMakeFiles/iss_switch.elf.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... disassemble_iss_switch"
	@echo "... get_calibration"
	@echo "... set_fuses"
	@echo "... get_fuses"
	@echo "... iss_switch"
	@echo "... iss_switch.elf"
	@echo "... rebuild_cache"
	@echo "... set_calibration"
	@echo "... get_status"
	@echo "... size"
	@echo "... upload_iss_switch"
	@echo "... upload_eeprom"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

